<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36836" started-at="2020-05-17T08:30:51Z" finished-at="2020-05-17T08:31:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36836" started-at="2020-05-17T08:30:51Z" finished-at="2020-05-17T08:31:28Z">
      <class name="com.ExtentReport.FailScrShotExtent">
        <test-method status="PASS" signature="extentsetUp()[pri:0, instance:com.ExtentReport.FailScrShotExtent@45c8e616]" name="extentsetUp" is-config="true" duration-ms="640" started-at="2020-05-17T14:00:51Z" finished-at="2020-05-17T14:00:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentsetUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ExtentReport.FailScrShotExtent@45c8e616]" name="setUp" is-config="true" duration-ms="28847" started-at="2020-05-17T14:00:52Z" finished-at="2020-05-17T14:01:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="logIn()[pri:0, instance:com.ExtentReport.FailScrShotExtent@45c8e616]" name="logIn" duration-ms="36" started-at="2020-05-17T14:01:21Z" finished-at="2020-05-17T14:01:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Free CRM #1 cloud software for any business large or small56] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Free CRM #1 cloud software for any business large or small56] but found [Google]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.ExtentReport.FailScrShotExtent.logIn(FailScrShotExtent.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.ExtentReport.FailScrShotExtent@45c8e616]" name="tearDown" is-config="true" duration-ms="5990" started-at="2020-05-17T14:01:21Z" finished-at="2020-05-17T14:01:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logIn status=FAILURE method=FailScrShotExtent.logIn()[pri:0, instance:com.ExtentReport.FailScrShotExtent@45c8e616] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="extentquit()[pri:0, instance:com.ExtentReport.FailScrShotExtent@45c8e616]" name="extentquit" is-config="true" duration-ms="1257" started-at="2020-05-17T14:01:27Z" finished-at="2020-05-17T14:01:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentquit -->
      </class> <!-- com.ExtentReport.FailScrShotExtent -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
